### ISSUE TITLE
Maximum supported php version missing

### ISSUE THREAD

**Issue by SimJoSt** [roots/wordpress#14]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

The current composer.json only contains a minimum php version, but is missing a maximum one. As the Wordpress project has to make changes to it's code to support it fully in version 5.3 (https://make.wordpress.org/core/2019/10/11/wordpress-and-php-7-4/), an open ended php requirement doesn't make sense.  
When using Wordpress through composer you expect it to support it to make use of the full feature set :)

## Steps to reproduce

1. all your project packages and dependencies to support php7.4 in your composer.json
2. have wordpress version set to 5.2.*
3. run composer update

**Expected behavior:** [What you expect to happen]
An error, that the package roots/wordpress doesn't fulfill the requirement of php >=7.4

**Actual behavior:** [What actually happens]
No errors and a php7.4 incompatible Wordpress version is installed.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time.

## Versions
+ roots/wordpress 5.2.* (5.3.* supports 7.4)
+ composer 1.10.5
+ macOS 10.15.4

## Additional information

I hope this is possible with the current automated setup.  
Keep up the great work!

**Comment by swalkinshaw** [comment]
Does WP itself ever specify a max version? Currently it just says "7.4 or greater": https://en-ca.wordpress.org/about/requirements/

**Comment by LeoColomb** [comment]
WP does not specify a max version, I'm afraid.
Nothing manageable from Roots perspective I guess.
