### ISSUE TITLE
Add a virtual package

### ISSUE THREAD

**Issue by mcaskill** [roots/wordpress#15]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

Add a [`provide` section](https://getcomposer.org/doc/04-schema.md#provide) with `wordpress/core-implementation` as a virtual package to all builds of WordPress.

Example:

```json
"provide": {
    "wordpress/core-implementation": "5.4.1"
}
```

## Motivation

This can be useful for WordPress plugins, themes, and libraries that are managed by Composer.

A library, such as johnbillion/extended-cpts, could list the WordPress versions that conflict that package:

```json
"conflict": {
    "wordpress/core-implementation": "<4.8"
}
```

A type of boilerplate could even require WordPress:

```json
"require": {
    "php": ">=7.1",
    "wordpress/core-implementation": ">=5.0"
}
```

## Additional context

John Bloch implemented this feature a few years ago (johnpbloch/build-wp#3)

**Comment by swalkinshaw** [comment]
Closing in favour of #22
