### ISSUE TITLE
Beta & Release Candidates Tags

### ISSUE THREAD

**Issue by thefrosty** [roots/wordpress#20]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

Would love to see beta and RC tagging if possible.

## Motivation

Testing future versions of WP, in this case our docker and composer is git managed and would be easier to bump require-dev for testing purposes.

## Additional context

Nope.

**Comment by tdwesten** [comment]
Yes!! Me Too! I want to run the WP beta 5.9 so i can use php 5.9 :)

**Comment by andronocean** [comment]
Ditto for wanting to try WP 5.9. What would the procedure be for making at least the RC versions available?

**Comment by krishaamer** [comment]
+1 want to test WordPress 6 beta release..

**Comment by retlehs** [comment]
see versions available at https://packagist.org/packages/roots/wordpress-full (via the new generator at https://github.com/roots/wordpress-packager)

**Comment by johnbillion** [comment]
Nice one! Thanks folks.
