### ISSUE TITLE
[GitHub repository] Latest release not marked as "Latest"

### ISSUE THREAD

**Issue by strarsis** [roots/wordpress#25]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description
The last release in this GitHub repository is not marked as "latest", instead `5.0.3` is.

## Steps to reproduce
Visit this GitHub repository, note that the latest repository is `5.0.3`.

**Expected behavior:** Latest release being actually the latest WordPress release.

**Actual behavior:** Latest release is `5.0.3` which is a very old release.

**Reproduces how often:** Always.

## Versions
(Not applicable)

**Comment by alwaysblank** [comment]
There are several releases shown here: https://github.com/roots/wordpress/releases Many of them are higher than 5.0.3, i.e. https://github.com/roots/wordpress/releases/tag/5.8. Can you provide more details about where any how you're encountering this problem?

**Comment by strarsis** [comment]
@alwaysblank: It seems that the latest release is not marked as `latest` in GitHub, hence release `5.0.3` is listed as `Latest`.

**Comment by swalkinshaw** [comment]
<img width="185" alt="image" src="https://user-images.githubusercontent.com/295605/132971520-7949d649-2afd-4539-8e9d-6d0ff4177e46.png">

I deleted the ~3 releases. Problem solved until we automatically create releases (ref: https://github.com/roots/wordpress/issues/1)
