### ISSUE TITLE
Old themes not in WordPress core 5.1 are installed with roots/wordpress

### ISSUE THREAD

**Issue by noelspringer** [roots/wordpress#3]
Themes currently installed with WP core 5.1 from both wordpress.org and the johnpbloch/wordpress composer package are:

* twentysixteen
* twentyseventeen
* twentynineteen

Themes installed with roots/wordpress include the above three themes as well as the old themes twentyeleven through to twentyfifteen.

**Comment by QWp6t** [comment]
This repo installs releases from the official [wordpress/wordpress](https://github.com/WordPress/WordPress/tree/5.1/wp-content/themes) repo.

**Comment by LeoColomb** [comment]
Actually @noelspringer is right.
And I'm not sure zip archives from mirrored git repo releases are the official distribution zips. It seems to be more that ones: https://wordpress.org/download/releases/.

**Comment by noelspringer** [comment]
Aha i see that repo includes the older themes. Curious though since the official WordPress releases don't include them.

Could the older themes have been removed from the official releases for security reasons?

**Comment by LeoColomb** [comment]
@noelspringer I guess old themes are kept in the sources for maintenance, but removed when building archives for distribution.

**Comment by noelspringer** [comment]
Makes sense Leo. Thanks

**Comment by retlehs** [comment]
![image](https://user-images.githubusercontent.com/115911/78508680-eb28f480-7745-11ea-9aea-94687ca29351.png)

let's start figuring out some options on what we can do to remove the old themes that aren't typically distributed with wordpress

**Comment by LeoColomb** [comment]
@retlehs One option available to exclude default themes is downloading "no-content" build from WordPress.org repo:

```
https://downloads.wordpress.org/release/wordpress-{$version}-no-content.zip
```

<small>PS: I've setup my own [WordPress-composer repo](https://github.com/LeoColomb/wordpress) where release use this option, but I would like to configure a [complete org with all the different available options](https://github.com/composer-wordpress).</small>

**Comment by austinpray** [comment]
@LeoColomb eventually we will finish https://github.com/roots/wordpress-packager which will allow releasing all three packages

- wordpress.org zip
- wordpress.org no-content zip
- git mirror

**Comment by LeoColomb** [comment]
@austinpray That would be awesome, indeed 🙂 
Let me know if I can help

**Comment by austinpray** [comment]
Looking at getting this fixed ASAP since this behavior triggers a security notice.

If anyone has time to experiment: it might be as simple as just adding some more metadata to the package to blacklist those old themes? https://getcomposer.org/doc/04-schema.md#archive

Also as far as rollout: pretty sure it's safe to assume that people will not mind if these themes disappear the next time they bump the roots/wordpress version?

**Comment by strarsis** [comment]
+1 for this! Having less unused files is always good.
