### ISSUE TITLE
[Unimportant issue] How often is the `cron` running?

### ISSUE THREAD

**Issue by strarsis** [roots/wordpress#30]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description
WordPress `5.8.2` was just advertised in the admin backend.
But the tag isn't available in the repository yet (the tag for the previous release `5.8.1` is).
How often does the `cron` run and check for new WordPress releases?

## Steps to reproduce

1. When a new WordPress release is advertised in the admin backend (or on WordPress website), 
check the releases of this repository. The tag isn't there yet.

**Expected behavior:**
Smaller `cron` intervals or a web hook/notification system for new official WordPress releases?

Maybe add a trigger URL so a developer can trigger it manually (with rate limiting of course).

**Actual behavior:**
Delay between new official WordPress release and available tag in repository.

**Reproduces how often:** It depends on when the new official release is published.
When the `cron` happens to run right afterwards it may appear instantaneous.

## Versions
(Not applicable)

**Comment by swalkinshaw** [comment]
It's running, just broken 😞  We think it's due to this change: https://make.wordpress.org/core/2021/11/10/default-git-branch-for-wordpress-wordpress-develop/

**Comment by swalkinshaw** [comment]
Turns out it has nothing to do with the above ^ and was just an issue with GitHub actions (I think). We took this chance to simplify the workflow in https://github.com/roots/wordpress/pull/31.

In case this ever happens again, we'll just manually trigger this action.

**Comment by strarsis** [comment]
@swalkinshaw: By the way: Is there a web hook that can be used that informs about new WordPress releases?

**Comment by swalkinshaw** [comment]
GitHub RSS feed for releases: https://github.com/WordPress/WordPress/releases.atom

**Comment by strarsis** [comment]
@swalkinshaw: Is this already used by this repository/cron? Hadn't looked into all code yet.

**Comment by swalkinshaw** [comment]
You can't trigger a GitHub workflow from an RSS feed unfortunately. So this repo just has a workflow which runs every 5 minutes that checks for new tags and is idempotent https://github.com/roots/wordpress/blob/5eb33524cd08833d54b8d104b858bec3c2d78aa7/bin/update-wp-releases.php#L48-L54
