### ISSUE TITLE
Bug: Uncaught Error: Call to undefined method WP_Object_Cache::add_multiple()

### ISSUE THREAD

**Issue by Preen** [roots/wordpress#40]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
After upgrading to 6.0 I get the following error.
Bug: Uncaught Error: Call to undefined method WP_Object_Cache::add_multiple() in .../web/wp/wp-includes/cache.php:65

#### What have you tried?
Downgrading and upgrading

#### Possible solutions
Have the up to date file with add_multiple function available
#### Temporary workarounds
I had to manually replace file contents from here to make it work again.
https://raw.githubusercontent.com/WordPress/WordPress/11691e8207ea24341a75c52f5777f09fa888ea28/wp-includes/class-wp-object-cache.php

### Steps To Reproduce

1. Install roots
2. Install woocommerce
3. install advanced custom forms 7 

### Expected Behavior

It working?

### Actual Behavior

It didnt work

### Relevant Log Output

```shell
2022/06/07 09:41:12 [error] 969#969: *909 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method WP_Object_Cache::add_multiple() in .../web/wp/wp-includes/cache.php:65
Stack trace:
#0 ../web/wp/wp-includes/taxonomy.php(3777): wp_cache_add_multiple()
#1 ../web/wp/wp-includes/taxonomy.php(3993): update_term_cache()
#2 ../web/wp/wp-includes/class-wp-term-query.php(813): _prime_term_caches()
#3 ../web/wp/wp-includes/class-wp-term-query.php(307): WP_Term_Query->get_terms()
#4 ../web/wp/wp-includes/taxonomy.php(1312): WP_Term_Query->query()
#5 ../web/wp/wp-includes/taxonomy.php(1099): get_terms()
#6 ../web/app/plugins/woocommerce/includes/class-wc-install.php(858): get_term_by()
#7 ../web/app/plugins/woocommerce/includes/class-wc-install.php(369): WC_Install::create_terms()
```

### Versions

6.0

**Comment by retlehs** [comment]
howdy! i'm unable to reproduce this. please post a topic over at https://discourse.roots.io/ if you still need support
