### ISSUE TITLE
Bug: As of WordPress 6.0, can no longer longer deploy if `preferred-install` is `source`

### ISSUE THREAD

**Issue by rkaiser0324** [roots/wordpress#41]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

In all previous WordPress versions, you were able to set up a Bedrock project even if the root composer `config.preferred-install` = "source". During development, for example, that is a preferable setting as it allows for easier debugging by leveraging the source control.

As of the update to support WordPress 6.0, however, it only works if preferred-install = "dist".  If you set it to source, you end up with `web/wp/` containing only `composer.json`, not the rest of WordPress.

#### What have you tried?

I think this started with WordPress 6.0; deploying Bedrock with 5.9.x is OK, although I will note that I was using earlier versions of `composer/installers` and some other dependencies so if those were the culprits it may have broken earlier.

#### What insights have you gained?

I suspect this happens because https://github.com/roots/wordpress-no-content/blob/main/composer.json only contains a "dist" key.

#### Possible solutions

`config.preferred-install` = "source" should be supported.

Since I can't see how bumping the WordPress version should be relevant to this deployment issue, I am logging this issue here. However it's possible it should be the root cause is actually in one of the dependencies; e.g., https://github.com/roots/wordpress-no-content, https://github.com/roots/wordpress-core-installer etc.

#### Temporary workarounds

Not aware of any.

### Steps To Reproduce

1. git checkout `roots/bedrock`.
2. Set config.preferred-install to "source" in the root composer.json
3. composer install
4. Check the contents of `web/wp` - only composer.json

I am using composer v2.2.3.  I don't have Subversion installed, only Git.

### Expected Behavior

`web/wp` should contain the WordPress source.

### Actual Behavior

`web/wp/` only contains `composer.json`.

### Relevant Log Output

```shell
[app-php8 root:/var/www] $ git clone https://github.com/roots/bedrock.git
Cloning into 'bedrock'...
remote: Enumerating objects: 2341, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 2341 (delta 5), reused 9 (delta 0), pack-reused 2321
Receiving objects: 100% (2341/2341), 773.91 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1189/1189), done.
[app-php8 root:/var/www] $ cd bedrock/
[app-php8 root:/var/www/bedrock] $ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 18 installs, 0 updates, 0 removals
    Failed to download wpackagist-theme/twentytwentytwo from source: svn was not found in your PATH, skipping source download
    Now trying to download from dist
  - Installing roots/wordpress-core-installer (1.100.0): Cloning 73f8488e51
  - Installing composer/installers (v2.1.0): Cloning 75e5ef0543
  - Installing symfony/polyfill-ctype (v1.24.0): Cloning 30885182c9
  - Installing oscarotero/env (v2.1.0): Cloning 0da22cadc6
  - Installing roave/security-advisories (dev-latest bac54e1)
  - Installing roots/bedrock-autoloader (1.0.4): Cloning f508348a33
  - Installing roots/bedrock-disallow-indexing (2.0.0): Cloning 6c28192e17
  - Installing roots/wordpress-no-content (6.0): Cloning e835336a33
  - Installing roots/wordpress (6.0.0)
  - Installing roots/wp-config (1.0.0): Cloning 37c3823079
  - Installing roots/wp-password-bcrypt (1.1.0): Cloning 15f0d8919f
  - Installing squizlabs/php_codesniffer (3.6.2): Cloning 5e4e71592f
  - Installing symfony/polyfill-php80 (v1.24.0): Cloning 57b712b08e
  - Installing symfony/polyfill-mbstring (v1.24.0): Cloning 0abb51d2f1
  - Installing phpoption/phpoption (1.8.1): Cloning eab7a0df01
  - Installing graham-campbell/result-type (v1.0.4): Cloning 0690bde053
  - Installing vlucas/phpdotenv (v5.4.1): Cloning 264dce589e
  - Installing wpackagist-theme/twentytwentytwo (1.2): Extracting archive
Generating optimized autoload files
14 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
[app-php8 root:/var/www/bedrock] $ composer --version
Composer version 2.2.3 2021-12-31 12:18:53
```

### Versions

2762d0a1961d942a9272155a8866b994f6af2c2c - CentOS 7.7, PHP 8.0.x

**Comment by LeoColomb** [comment]
> Would someone expect the source of a specific tag/ref?

Actually yes, it usually use a reference (commit or tag) provided with the `source` attribute.
It is expected in the way that switching `preferred-install` between `source` or `dist` should provide the exact same content but one with the complete git context (from where you can checkout something else and do your stuff).

Here for example `monolog/monolog` from the API:

```json
{
    "version": "3.0.0",
    "source": {
        "url": "https://github.com/Seldaek/monolog.git",
        "type": "git",
        "reference": "60ad5183b5e5d6c9d4047e9f3072d36071dcc161"
    },
    "dist": {
        "url": "https://api.github.com/repos/Seldaek/monolog/zipball/60ad5183b5e5d6c9d4047e9f3072d36071dcc161",
        "type": "zip",
        "shasum": "",
        "reference": "60ad5183b5e5d6c9d4047e9f3072d36071dcc161"
    },
    ...
}
```
