### ISSUE TITLE
Bug: New minor WordPress versions not available

### ISSUE THREAD

**Issue by Rahe** [roots/wordpress#44]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

New minor versions of WordPress not all availabe, for example 4.9.21 is on https://fr.wordpress.org/download/releases/ but not available for update throug composer.

#### What have you tried?

composer update with a 4.9.* or 4.9.21

#### What insights have you gained?

No update or error

### Steps To Reproduce

1. Set roots/wordpress for 4.9.21
2. Composer install

### Expected Behavior

Update or install version

### Actual Behavior

4.9.20 is installer.

### Relevant Log Output

```shell
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires roots/wordpress 4.9.21, found roots/wordpress[dev-main, dev-nightly, 4.0, ..., 4.9.20, 5.0, ..., 5.9.4, 6.0, 6.0.1, 6.0.2] but it does not match the constraint.
```

### Versions

macos

**Comment by retlehs** [comment]
Thank you for the report! We're investigating how this meta package isn't publishing all the releases, but in the meantime you can use either `roots/wordpress-no-content` or `roots/wordpress-full`, both of which contain all of the expected versions

**Comment by LeoColomb** [comment]
Thanks @Rahe, good catch!
This is now fixed via https://github.com/roots/wordpress-packager/pull/588

**Comment by Rahe** [comment]
Thx a lot :)

**Comment by Rahe** [comment]
Hello,

I'm commenting this again because I had the same issue with one more version :
`- Root composer.json requires roots/wordpress 4.9.23, found roots/wordpress[dev-main, dev-nightly, 3.7.38, ..., 3.9.37, 4.0, ..., 4.9.22, 5.0, ..., 5.9.7, 6.0, ..., 6.2.2] but it does not match the constraint.`

Is this the same problem ?

**Comment by LeoColomb** [comment]
@Rahe Yes, the same… 😭
Should be fixed by https://github.com/roots/wordpress-packager/pull/743, and these versions should be available at next run after the merge.
I hope at the next release announcement, WordPress' team won't tag more than 50 versions 🤞

**Comment by LeoColomb** [comment]
https://packagist.org/packages/roots/wordpress#4.9.23
