### ISSUE TITLE
Some old minor versions are not available

### ISSUE THREAD

**Issue by petitphp** [roots/wordpress#48]
### Version

4.9.26

### What did you expect to happen?

Follow up to #44 

Following the security release for WordPress 6.5.5, I want to update my dependency to `roots/wordpress` 4.9.26.

### What actually happens?

Package `roots/wordpress` 4.9.26 is not available.

### Steps to reproduce

Update the version in composer.json :
```json
"roots/wordpress": "4.9.26",
```

Run `composer update`

### Log output

```shell
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires roots/wordpress 4.9.26 (exact version match: 4.9.26 or 4.9.26.0), found roots/wordpress[dev-main, 3.7.38, ..., 3.9.40, 4.0, ..., 4.9.25, 5.0, ..., 5.9.10, 6.0, ..., 6.5.5] but it does not match the constraint.
```

### Please confirm this isn't a support request.

Yes

**Comment by retlehs** [comment]
:eyes: @LeoColomb do we need to bump the per page value again?

https://github.com/roots/wordpress-packager/pull/743
https://github.com/roots/wordpress-packager/pull/588

**Comment by LeoColomb** [comment]
I'm afraid we are already at the max value for the `per_page` attribute: https://docs.github.com/fr/rest/repos/repos?apiVersion=2022-11-28#list-repository-tags
An additional page can be requested, but I guess the algorithm to fetch the tags has to be reviewed.
I'll take a look and see what can be done.

**Comment by LeoColomb** [comment]
At least the missing releases should be available now.
