### ISSUE TITLE
.git directory is included in the package and its not safe for public view

### ISSUE THREAD

**Issue by alexbogias** [roots/wordpress#49]
### Version

6.5.5

### What did you expect to happen?

.git directory should not be downloaded with composer update

### What actually happens?

.git directory is being downloaded with composer update

### Steps to reproduce

composer update
ls -la web/wp/.git

### Please confirm this isn't a support request.

Yes

**Comment by retlehs** [comment]
These steps to reproduce aren't valid

You can also confirm this isn't a valid bug by installing the latest version of Bedrock, which was just tagged with WP 6.5.5
