### ISSUE TITLE
Branches don't appear to be synced any more, or have been deleted

### ISSUE THREAD

**Issue by roborourke** [roots/wordpress#50]
### Version

dev-nightly

### What did you expect to happen?

The unit tests for our plugin rely on the `dev-nightly` or `nightly` branch from this repo, but all branches except for `main` appear to have disappeared. I would expect these to remain in place even if stale given the purpose of this repo.

### What actually happens?

Branches other than `main` are missing.

### Steps to reproduce

```
composer require roots/wordpress:dev-nightly
```

### Please confirm this isn't a support request.

Yes, No

**Comment by LeoColomb** [comment]
Thanks for opening this issue @roborourke.
Nightly branches have been merged into `main` branches while we transitioned to the [new package delivery system](https://roots.io/updates-to-roots-wordpress-composer-package/) we put in place a few years ago.
In short, `main` branches can be used in the exact same way as `nightly` before, using the composer tag `dev-main`:
```console
composer require roots/wordpress:dev-main
```

**Comment by roborourke** [comment]
Thanks @LeoColomb - sorry I looked for some sort of announcement but clearly not hard enough 🤦‍♂️  . I'll update our relevant GH actions.

Happy for this to be closed out.
